### ISSUE TITLE
window下 kotlin build 时 generatePluginComponentsIdx 无法通过

### ISSUE THREAD

**Issue by mashirot** [halo-sigs/halo-gradle-plugin#12]
问题在这行的 `Paths.get(buildPath)`
https://github.com/halo-sigs/halo-gradle-plugin/blob/3246918863c296d4b5fa283affd61ea6245caff3/src/main/java/run/halo/gradle/PluginComponentsIndexTask.java#L68

```text
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generatePluginComponentsIdx'.

Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 61: D:\Java Project\halo-plugin-typecho\build\classes\java\main;D:\Java Project\halo-plugin-typecho\build\classes\kotlin\main
	at run.halo.gradle.PluginComponentsIndexTask.generate(PluginComponentsIndexTask.java:68)
```

build下目录结构为：

```text
build
├─classes
│  └─kotlin
│      └─main
│          ├─io
│          │  └─sakurasou
│          │      └─halo
│          │          └─typecho
│          │              ├─controller
│          │              ├─entity
│          │              ├─service
│          │              └─util
│          └─META-INF
├─kotlin
│  └─compileKotlin
│      ├─cacheable
│      │  └─caches-jvm
│      │      ├─inputs
│      │      ├─jvm
│      │      │  └─kotlin
│      │      └─lookups
│      ├─classpath-snapshot
│      └─local-state
└─resources
    └─main
        └─console
```

不清楚 `buildPath` 为什么会有java的路径，大概率与 `ConfigurableFileCollection classesDirs = getProject().getObjects().fileCollection();` 有关

**Comment by mashirot** [comment]
demo请看https://github.com/mashirot/halo-plugin-typecho/tree/temp

**Comment by guqing** [comment]
感谢反馈🥸，晚些时候会尝试复现一下，你可以先使用传统方式进行插件运行

**Comment by mashirot** [comment]
> 感谢反馈🥸，晚些时候会尝试复现一下，你可以先使用传统方式进行插件运行

这就是传统方式，`gradle build` 的时候

**Comment by JohnNiang** [comment]
经过实际构建后发现，当前问题仅在 Windows 上有问题。因为 `sourceSets.main.output.classesDirs` 返回了两个路径，导致 Windows 操作系统上无法创建路径为 `D:\Java Project\halo-plugin-typecho\build\classes\java\main;D:\Java Project\halo-plugin-typecho\build\classes\kotlin\main\plugin-components.idx` 文件，在 Linux 或者 macOS 下可以正常创建。

实际上在 generatePluginComponentsIdx 任务的最后阶段会把 plugin-components.idx 靠背到 META-INF 下，所以 idx 文件的位置在哪里并不重要。

可能的解决方案：idx 文件路径不使用 classesDirs 即可。

**Comment by JohnNiang** [comment]
Closed by https://github.com/halo-sigs/halo-gradle-plugin/pull/13

/close
/kind bug
