### ISSUE TITLE
添加yaml文件和config目录支持

### ISSUE THREAD

**Issue by minliacom** [halo-sigs/halo-gradle-plugin#3]
可以为 addition properties 添加yaml文件和config目录支持吗

**Comment by guqing** [comment]
后续会考虑，不过此仓库目前计划废弃 halo jar 的启动方式，改为基于 docker 的容器话开发，目前 jar 要准备一个环境太复杂了，而且 halo 并不计划支持 jar 包部署，所以使用 docker 来开发和调试插件将是不错的选择，目前正在推进，很快就可以使用。
待基于 docker 环境的插件开发功能做好会根据情况提供更方便的配置方式。

**Comment by minliacom** [comment]
能用docker开发太好了，和运行环境保持同样的开发环境，大爱！

**Comment by guqing** [comment]
目前已支持自定义配置，启动 haloServer 或 watch 任务后会将 halo 工作目录挂在到插件项目的 workplace 目录下，可以在 workplace 目录添加一个 config 目录并添加 application.yaml 文件用于覆盖默认配置，如：
```
workplace
├── config
│   └── application.yaml
```
其中 application.yaml 的内容如下：
```yaml
logging:
  level:
    run.halo.app: DEBUG
```
此示例用于配置 Halo 的日志级别为 DEBUG
