### ISSUE TITLE
插件更新时提供一个版本号迭代的机制

### ISSUE THREAD

**Issue by minliacom** [halo-sigs/halo-gradle-plugin#4]
在插件开发过程中，要修改好几个地方进行版本号变化，需要一个好的机制来更新版本号

1. package.json
"version": "1.0.1"

2. ./src/main/resources/plugin.yaml
spec:
  version: 1.0.1

3. gradle.properties
version=1.0.1

**Comment by guqing** [comment]
非常好的提议，目前此插件是提供了自动更新 plugin.yaml 的版本号的不过在 github action 上有点 bug 它没生效，暂时太忙了会尽快修复

**Comment by guqing** [comment]
由于目前已经支持通过 gradle 参数 -Pversion=xxx 或者通过 gradle.properties 来指定，因此将关闭此 issue
